### PR TITLE
Cleanup thread cleaning and fix PinPAD crash

### LINKED ISSUE #346: bug: crash in pinpad code
Something along the lines of "enter wrong pin, think what's wrong, enter right pin", probably at the edge of the timer for original timeout, results in crash.
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               web-eid-safari [47862]
Path:                  /Applications/web-eid-safari.app/Contents/MacOS/web-eid-safari
Identifier:            eu.web-eid.web-eid-safari
Version:               2.6.0 (654)
App Item ID:           1576665083
App External ID:       869372367
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-10-25 11:11:57.2612 +0300
OS Version:            macOS 15.1 (24B82)
Report Version:        12
Anonymous UUID:        1ED5F241-E647-A999-2A7A-AC6527A04FAD


Time Awake Since Boot: 260000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Codes:       0x0000000000000001, 0x0000000000000008

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [47862]

VM Region Info: 0x8 is not in any region.  Bytes before following region: 4308336632
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      100cc0000-100f5c000    [ 2672K] r-x/r-x SM=COW  /Applications/web-eid-safari.app/Contents/MacOS/web-eid-safari

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   QtWidgets                     	       0x102add0e4 QProgressBar::maximum() const + 0
1   web-eid-safari                	       0x100cfab2c 0x100cc0000 + 240428
2   QtCore                        	       0x103b5dc88 0x103a90000 + 842888
3   QtCore                        	       0x103cb7ad8 0x103a90000 + 2259672
4   QtCore                        	       0x103b560d0 QObject::event(QEvent*) + 88
5   QtWidgets                     	       0x102930d1c QApplicationPrivate::notify_helper(QObject*, QEvent*) + 272
6   QtWidgets                     	       0x102931b70 QApplication::notify(QObject*, QEvent*) + 504
7   QtCore                        	       0x103b126bc QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
8   QtCore                        	       0x103c85a84 QTimerInfoList::activateTimers() + 1096
9   libqcocoa.dylib               	       0x1024b5b9c 0x1024a0000 + 88988
10  web-eid-safari                	       0x100ceda08 Controller::waitForChildThreads() + 112
11  web-eid-safari                	       0x100ced988 Controller::exit() + 52
12  QtCore                        	       0x103b5dc88 0x103a90000 + 842888
13  QtCore                        	       0x103b5546c QObject::destroyed(QObject*) + 64
14  QtWidgets                     	       0x10296c884 QWidget::~QWidget() + 1088
15  web-eid-safari                	       0x100cf6334 WebEidDialog::~WebEidDialog() + 68
16  QtCore                        	       0x103b56328 QObject::event(QEvent*) + 688
17  QtWidgets                     	       0x10297d39c QWidget::event(QEvent*) + 3656
18  web-eid-safari                	       0x100cf9814 WebEidDialog::event(QEvent*) + 252
19  QtWidgets                     	       0x102930d1c QApplicationPrivate::notify_helper(QObject*, QEvent*) + 272
20  QtWidgets                     	       0x10293262c QApplication::notify(QObject*, QEvent*) + 3252
21  QtCore                        	       0x103b126bc QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
22  QtCore                        	       0x103b139a4 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 1464
23  libqcocoa.dylib               	       0x1024b73b4 0x1024a0000 + 95156
24  libqcocoa.dylib               	       0x1024b846c 0x1024a0000 + 99436
25  CoreFoundation                	       0x19a481d34 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
26  CoreFoundation                	       0x19a481cc8 __CFRunLoopDoSource0 + 176
27  CoreFoundation                	       0x19a481a2c __CFRunLoopDoSources0 + 244
28  CoreFoundation                	       0x19a4805c8 __CFRunLoopRun + 840
29  CoreFoundation                	       0x19a47fbc4 CFRunLoopRunSpecific + 588
30  HIToolbox                     	       0x1a58eff64 RunCurrentEventLoopInMode + 292
31  HIToolbox                     	       0x1a58f5d54 ReceiveNextEventCommon + 636
32  HIToolbox                     	       0x1a58f5eb8 _BlockUntilNextEventMatchingListInModeWithFilter + 76
33  AppKit                        	       0x19dfaba08 _DPSNextEvent + 660
34  AppKit                        	       0x19e8ebe0c -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
35  AppKit                        	       0x19df9eae0 -[NSApplication run] + 480
36  libqcocoa.dylib               	       0x1024b6000 0x1024a0000 + 90112
37  QtCore                        	       0x103b1c214 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 540
38  web-eid-safari                	       0x100cc94f0 0x100cc0000 + 38128
39  CoreFoundation                	       0x19a476800 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 148
40  CoreFoundation                	       0x19a50766c ___CFXRegistrationPost_block_invoke + 88
41  libdispatch.dylib             	       0x19a1e68f8 _dispatch_call_block_and_release + 32
42  libdispatch.dylib             	       0x19a1e8658 _dispatch_client_callout + 20
43  libdispatch.dylib             	       0x19a1f6f68 _dispatch_main_queue_drain + 980
44  libdispatch.dylib             	       0x19a1f6b84 _dispatch_main_queue_callback_4CF + 44
45  CoreFoundation                	       0x19a4c0e60 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
46  CoreFoundation                	       0x19a480a4c __CFRunLoopRun + 1996
47  CoreFoundation                	       0x19a47fbc4 CFRunLoopRunSpecific + 588
48  HIToolbox                     	       0x1a58eff64 RunCurrentEventLoopInMode + 292
49  HIToolbox                     	       0x1a58f5d54 ReceiveNextEventCommon + 636
50  HIToolbox                     	       0x1a58f5eb8 _BlockUntilNextEventMatchingListInModeWithFilter + 76
51  AppKit                        	       0x19dfaba08 _DPSNextEvent + 660
52  AppKit                        	       0x19e8ebe0c -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
53  AppKit                        	       0x19df9eae0 -[NSApplication run] + 480
54  libqcocoa.dylib               	       0x1024b6000 0x1024a0000 + 90112
55  QtCore                        	       0x103b1c214 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 540
56  QtCore                        	       0x103b12d10 QCoreApplication::exec() + 112
57  web-eid-safari                	       0x100cc9cbc main + 336
58  dyld                          	       0x19a018274 start + 2840

Thread 1:
0   libsystem_pthread.dylib       	       0x19a3960e8 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x19a3960e8 start_wqthread + 0

Thread 3:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x19a359e34 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x19a36c5d0 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x19a3629d8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x19a35a17c mach_msg + 24
4   CoreFoundation                	       0x19a481edc __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x19a48073c __CFRunLoopRun + 1212
6   CoreFoundation                	       0x19a47fbc4 CFRunLoopRunSpecific + 588
7   AppKit                        	       0x19e0d0b8c _NSEventThread + 148
8   libsystem_pthread.dylib       	       0x19a39b2e4 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x19a3960fc thread_start + 8

Thread 4:
0   libsystem_pthread.dylib       	       0x19a3960e8 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x19a3960e8 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	       0x19a3960e8 start_wqthread + 0

Thread 7:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x19a35d5cc __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x19a39b894 _pthread_cond_wait + 1204
2   QtCore                        	       0x103c93940 0x103a90000 + 2111808
3   QtCore                        	       0x103c937f4 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x103c8e018 0x103a90000 + 2088984
5   QtCore                        	       0x103c86b2c 0x103a90000 + 2059052
6   libsystem_pthread.dylib       	       0x19a39b2e4 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x19a3960fc thread_start + 8

Thread 8:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x19a35d5cc __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x19a39b894 _pthread_cond_wait + 1204
2   QtCore                        	       0x103c93940 0x103a90000 + 2111808
3   QtCore                        	       0x103c937f4 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x103c8e018 0x103a90000 + 2088984
5   QtCore                        	       0x103c86b2c 0x103a90000 + 2059052
6   libsystem_pthread.dylib       	       0x19a39b2e4 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x19a3960fc thread_start + 8

Thread 9:
0   libsystem_pthread.dylib       	       0x19a3960e8 start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib       	       0x19a3960e8 start_wqthread + 0


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000019   x2: 0x00006000035af210   x3: 0x0000000000000004
    x4: 0x0000000000000005   x5: 0x00000000b24148a1   x6: 0x00006000035af200   x7: 0x0000000000000003
    x8: 0x000000013afd4ad0   x9: 0x0000000000000000  x10: 0x0000000000000019  x11: 0x0000000000000018
   x12: 0x0000000000000000  x13: 0x00006000035af240  x14: 0x000000011c810e4e  x15: 0x00000000000007fb
   x16: 0x0000000102add0e4  x17: 0x00000000000000a0  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x0000000000000003  x21: 0x0000600003280300  x22: 0x000000016f13bd90  x23: 0x00000001ff4af840
   x24: 0x0000600002787300  x25: 0x00006000032f1860  x26: 0x000060000188e100  x27: 0x00006000016fa9a0
   x28: 0x00000001ff4af840   fp: 0x000000016f13bc60   lr: 0x0000000100cfab2c
    sp: 0x000000016f13bc10   pc: 0x0000000102add0e4 cpsr: 0x60001400
   far: 0x0000000000000008  esr: 0x92000006 (Data Abort) byte read Translation fault

Binary Images:
       0x100cc0000 -        0x100f5bfff eu.web-eid.web-eid-safari (2.6.0) <21b75f51-283d-3d30-81d0-e00d545b2dd4> /Applications/web-eid-safari.app/Contents/MacOS/web-eid-safari
       0x1018a4000 -        0x101c17fff libcrypto.3.dylib (*) <4d83aefd-ed76-3f38-9da1-ac282b16a7ae> /Applications/web-eid-safari.app/Contents/Frameworks/libcrypto.3.dylib
       0x1012cc000 -        0x1013f3fff org.qt-project.QtNetwork (6.7) <c8b16a8e-22b8-33a2-8cfa-debc12962370> /Applications/web-eid-safari.app/Contents/Frameworks/QtNetwork.framework/Versions/A/QtNetwork
       0x100fdc000 -        0x100fe3fff org.qt-project.QtSvgWidgets (6.7) <c244733b-c0b2-3baf-9df5-759e44da41f5> /Applications/web-eid-safari.app/Contents/Frameworks/QtSvgWidgets.framework/Versions/A/QtSvgWidgets
       0x1010ec000 -        0x101133fff org.qt-project.QtSvg (6.7) <46007668-ea4b-35a1-bfc0-4d94329a2ac4> /Applications/web-eid-safari.app/Contents/Frameworks/QtSvg.framework/Versions/A/QtSvg
       0x102924000 -        0x102d8bfff org.qt-project.QtWidgets (6.7) <46918f03-284d-3238-b37f-edd91373d535> /Applications/web-eid-safari.app/Contents/Frameworks/QtWidgets.framework/Versions/A/QtWidgets
       0x101d08000 -        0x10235bfff org.qt-project.QtGui (6.7) <5320e1a3-020c-3308-9946-bc8b01353847> /Applications/web-eid-safari.app/Contents/Frameworks/QtGui.framework/Versions/A/QtGui
       0x103a90000 -        0x103f37fff org.qt-project.QtCore (6.7) <60ab95ca-10b1-39e5-bd2b-80868c45c0df> /Applications/web-eid-safari.app/Contents/Frameworks/QtCore.framework/Versions/A/QtCore
       0x100ff8000 -        0x101087fff libssl.3.dylib (*) <21efa13b-0b24-3615-99ef-906a6a142ea1> /Applications/web-eid-safari.app/Contents/Frameworks/libssl.3.dylib
       0x101458000 -        0x1014d7fff org.qt-project.QtDBus (6.7) <f1dcad16-9f81-3122-b6b4-5e44c5e37731> /Applications/web-eid-safari.app/Contents/Frameworks/QtDBus.framework/Versions/A/QtDBus
       0x101214000 -        0x101233fff com.apple.security.csparser (3.0) <db365164-e7d4-3315-a4bf-a306666f29d7> /System/Library/Frameworks/Security.framework/Versions/A/PlugIns/csparser.bundle/Contents/MacOS/csparser
       0x1024a0000 -        0x10253ffff libqcocoa.dylib (*) <2e11d1b9-c768-31f8-98e9-22c70a78e8fb> /Applications/web-eid-safari.app/Contents/PlugIns/platforms/libqcocoa.dylib
       0x1028e0000 -        0x102903fff libqmacstyle.dylib (*) <f4592017-b644-3f41-b95c-bd0dfe46202e> /Applications/web-eid-safari.app/Contents/PlugIns/styles/libqmacstyle.dylib
       0x102858000 -        0x10285ffff libqgif.dylib (*) <ec9de7ce-97ec-3731-af87-a46a1328e3d8> /Applications/web-eid-safari.app/Contents/PlugIns/imageformats/libqgif.dylib
       0x102870000 -        0x102877fff libqico.dylib (*) <f61952d1-1aca-31a6-812c-f414c9158e9c> /Applications/web-eid-safari.app/Contents/PlugIns/imageformats/libqico.dylib
       0x1039cc000 -        0x103a33fff libqjpeg.dylib (*) <83cf3354-3294-3c2f-96b2-e908b6bb533c> /Applications/web-eid-safari.app/Contents/PlugIns/imageformats/libqjpeg.dylib
       0x102888000 -        0x10288ffff libqsvg.dylib (*) <3832b71b-12ed-3d44-b6c6-ea5753e63cb2> /Applications/web-eid-safari.app/Contents/PlugIns/imageformats/libqsvg.dylib
       0x103a48000 -        0x103a53fff libobjc-trampolines.dylib (*) <f1242604-dcb7-30a9-a19a-182991e6e645> /usr/lib/libobjc-trampolines.dylib
       0x11a2f8000 -        0x11aa1bfff com.apple.AGXMetalG14X (322.10) <f6817cf9-b70f-382a-839f-1fdd973b9138> /System/Library/Extensions/AGXMetalG14X.bundle/Contents/MacOS/AGXMetalG14X
       0x10ff80000 -        0x10ffa7fff libqopensslbackend.dylib (*) <3f01fa20-ab1c-3443-a939-45d5ed5b6937> /Applications/web-eid-safari.app/Contents/PlugIns/tls/libqopensslbackend.dylib
       0x10fc84000 -        0x10fc93fff libqcertonlybackend.dylib (*) <c44a32a4-8784-3299-a06e-ae1294ff7fa1> /Applications/web-eid-safari.app/Contents/PlugIns/tls/libqcertonlybackend.dylib
       0x10fca4000 -        0x10fcaffff libqsvgicon.dylib (*) <a4a6007d-9ee7-3e48-9cc6-5bde970694f4> /Applications/web-eid-safari.app/Contents/PlugIns/iconengines/libqsvgicon.dylib
       0x19a404000 -        0x19a8f8fff com.apple.CoreFoundation (6.9) <ae4610f8-7c5c-3484-858e-cae7457d206e> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x1a57e4000 -        0x1a5aebfff com.apple.HIToolbox (2.1.1) <738685cb-aca1-3dfe-91c5-192bab97a042> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x19df71000 -        0x19f36cfff com.apple.AppKit (6.9) <49d8b1b6-0ea8-36ad-89fd-a41acf00a742> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x19a1e4000 -        0x19a22afff libdispatch.dylib (*) <9ea577db-73c2-39d8-9fc0-544fa595a142> /usr/lib/system/libdispatch.dylib
       0x19a012000 -        0x19a0947b3 dyld (*) <6beafde4-b011-3e47-8aae-4d7b6e4bb7e8> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x19a394000 -        0x19a3a0fff libsystem_pthread.dylib (*) <3b8268be-4e02-3b4a-8b41-baed2bbaacff> /usr/lib/system/libsystem_pthread.dylib
       0x19a359000 -        0x19a393ff7 libsystem_kernel.dylib (*) <9fea25a4-e8ca-3f3d-901c-a53ff2bc7217> /usr/lib/system/libsystem_kernel.dylib

```

### PR DESCRIPTION
**Pull request by metsma**
Fixes #346

Signed-off-by: Raul Metsma <raul@metsma.ee>

### CODE REVIEW

File: src/controller/threads/controllerchildthread.hpp [hunk 1]
```diff
@@ -27,10 +27,13 @@
 #include "qeid.hpp"
 #include "logging.hpp"
 
-#include <QThread>
+#include <QCoreApplication>
 #include <QMutexLocker>
+#include <QThread>
 #include <QWaitCondition>
 
+using namespace std::chrono;
```
Comment (mrts) [inline src/controller/threads/controllerchildthread.hpp:35]: It is better to avoid namespace pollution, especially as the time units are used only in four locations:

```diff
diff --git a/src/controller/controller.cpp b/src/controller/controller.cpp
index 90040bf..07affa1 100644
--- a/src/controller/controller.cpp
+++ b/src/controller/controller.cpp
@@ -327,6 +327,8 @@ void Controller::exit()
 
 void Controller::waitForChildThreads()
 {
+    using namespace std::chrono;
+
     for (auto* thread : findChildren<QThread*>()) {
         qDebug() << "Interrupting thread" << uintptr_t(thread);
         thread->disconnect();
diff --git a/src/controller/threads/cardeventmonitorthread.hpp b/src/controller/threads/cardeventmonitorthread.hpp
index cb29ca2..55dda90 100644
--- a/src/controller/threads/cardeventmonitorthread.hpp
+++ b/src/controller/threads/cardeventmonitorthread.hpp
@@ -39,6 +39,8 @@ public:
 
     void run() override
     {
+        using namespace std::chrono;
+
         QMutexLocker lock {&controllerChildThreadMutex};
 
         qDebug() << "Starting" << metaObject()->className() << uintptr_t(this) << "for command"
@@ -87,6 +89,8 @@ private:
 
     eid_ptr_vector getSupportedCardsIgnoringExceptions()
     {
+        using namespace std::chrono;
+
         while (!isInterruptionRequested()) {
             try {
                 return electronic_id::availableSupportedCards();
diff --git a/src/controller/threads/controllerchildthread.hpp b/src/controller/threads/controllerchildthread.hpp
index 34c2220..a58aa6b 100644
--- a/src/controller/threads/controllerchildthread.hpp
+++ b/src/controller/threads/controllerchildthread.hpp
@@ -32,8 +32,6 @@
 #include <QThread>
 #include <QWaitCondition>
 
-using namespace std::chrono;
-
 class ControllerChildThread : public QThread
 {
     Q_OBJECT
diff --git a/src/controller/threads/waitforcardthread.hpp b/src/controller/threads/waitforcardthread.hpp
index 67049e3..b1f2492 100644
--- a/src/controller/threads/waitforcardthread.hpp
+++ b/src/controller/threads/waitforcardthread.hpp
@@ -41,6 +41,8 @@ signals:
 private:
     void doRun() override
     {
+        using namespace std::chrono;
+
         while (!attemptCardSelection() && !isInterruptionRequested()) {
             waitForControllerNotify.wait(&controllerChildThreadMutex, 1s);
         }
```

File: src/controller/controller.cpp [hunk 2]
```diff
@@ -213,51 +185,32 @@ void Controller::runCommandHandler(const std::vector<ElectronicID::ptr>& availab
...
 {
-    CardEventMonitorThread* cardEventMonitorThread =
-        new CardEventMonitorThread(this, std::string(commandType()));
-    saveChildThreadPtrAndConnectFailureFinish(cardEventMonitorThread);
-    cardEventMonitorThreadKey = uintptr_t(cardEventMonitorThread);
+    auto* cardEventMonitorThread = new CardEventMonitorThread(this, commandType());
+    connect(cardEventMonitorThread, &ControllerChildThread::failure, this,
+            &Controller::onCriticalFailure);
+    connect(this, &Controller::stopCardEventMonitorThread, cardEventMonitorThread,
+            &WaitForCardThread::requestInterruption);
```
Comment (mrts) [inline src/controller/controller.cpp:192]: As `cardEventMonitorThread` is `CardEventMonitorThread*`, connect to `&CardEventMonitorThread::requestInterruption`:
```suggestion
            &CardEventMonitorThread::requestInterruption);
```

File: src/controller/controller.cpp [hunk 3]
```diff
@@ -213,51 +185,32 @@ void Controller::runCommandHandler(const std::vector<ElectronicID::ptr>& availab
...
-
 void Controller::disposeUI()
 {
-    if (window) {
-        window->disconnect();
-        // As the Qt::WA_DeleteOnClose flag is set, the dialog is deleted automatically.
-        window->close();
-        window = nullptr;
-    }
+    delete window;
```
Comment (mrts) [inline src/controller/controller.cpp:199]: This simplification reduces safety, so I suggest to revert this. If you really want immediate deletion, you can use `window->deleteLater()` after `close()`:

```c++
    if (window) {
        window->disconnect();
        // As the Qt::WA_DeleteOnClose flag is set, this will delete the dialog automatically.
        window->close();
        window->deleteLater();
        window = nullptr;
    }
```

File: src/controller/controller.cpp [hunk 4]
```diff
@@ -373,18 +327,15 @@ void Controller::exit()
 
 void Controller::waitForChildThreads()
 {
-    // Waiting for child threads must not happen in destructor.
-    // See https://tombarta.wordpress.com/2008/07/10/gcc-pure-virtual-method-called/ for details.
```
Comment (mrts) [inline src/controller/controller.cpp:377]: Keep the comment, it is useful.

**Review by mrts — CHANGES_REQUESTED** [review]
Thanks, very nice simplification of the thread management 👍 !

File: src/controller/controller.cpp (hunk 3 above)
Comment (metsma) [reply src/controller/controller.cpp:199]: It is perfectly valid free and delete null pointer.
https://en.cppreference.com/w/cpp/memory/new/operator_delete.html

> 1) If ptr is null, does nothing. Otherwise, reclaims the storage allocated by the earlier call to [operator new](https://en.cppreference.com/w/cpp/memory/new/operator_new.html).

Comment (mrts) [reply src/controller/controller.cpp:199]: Right, but when using `close()` and  `deleteLater()` it is required. And Qt docs warn that not using `deleteLater()` may crash if the object is deleted while it is handling an event.

**Review by mrts — APPROVED** [review]

File: src/controller/controller.cpp [hunk 5]
```diff
@@ -324,67 +273,56 @@ void Controller::onDialogOK(const EidCertificateAndPinInfo& certAndPinInfo)
...
-                QCoreApplication::processEvents();
-            }
+    for (auto* thread : findChildren<QThread*>()) {
+        qDebug() << "Interrupting thread" << uintptr_t(thread);
+        thread->disconnect();
+        thread->requestInterruption();
+        ControllerChildThread::waitForControllerNotify.wakeAll();
+        while (thread->isRunning()) {
+            using namespace std::chrono_literals;
+            thread->wait(100ms);
```
Comment (mrts) [inline src/controller/controller.cpp:325]: The 100 millisecond wait made only sense along with event processing, recommend to add it back:

```suggestion
            thread->wait(100ms);
            QCoreApplication::processEvents();
```

Otherwise the while loop does not have a purpose, it is equivalent to just waiting indefinitely.

File: src/controller/controller.cpp [hunk 6]
```diff
@@ -324,67 +273,56 @@ void Controller::onDialogOK(const EidCertificateAndPinInfo& certAndPinInfo)
...
         // This should not happen, and when it does, OK should be equivalent to cancel.
-        onPinPadCancel();
+        onDialogCancel();
     }
 }
 
 void Controller::onDialogCancel()
 {
-    REQUIRE_NON_NULL(window)
-
```
Comment (mrts) [inline src/controller/controller.cpp:334]: Shouldn't you `emit stopCardEventMonitorThread()` here?

File: tests/mock-ui/mock-ui.cpp [hunk 7]
```diff
@@ -25,8 +25,7 @@
 
 WebEidUI* WebEidUI::createAndShowDialog(const CommandType)
 {
-    static MockUI instance;
-    return &instance;
+    return new MockUI;
```
Comment (mrts) [inline tests/mock-ui/mock-ui.cpp:28]: This leaks, no parent nor `WA_DeleteOnClose`. Should you add `WA_DeleteOnClose`?

**Review by mrts — CHANGES_REQUESTED** [review]

File: src/controller/controller.cpp (hunk 5 above)
Comment (metsma) [reply src/controller/controller.cpp:325]: All calls waitForChildThreads() are after disposeUI, no point to process any more events.
and timer makes sure that function does not continue before all thread are ended

File: src/controller/controller.cpp (hunk 6 above)
Comment (metsma) [reply src/controller/controller.cpp:334]: I do not see that there can be any running thread at this point

File: src/controller/controller.cpp (hunk 5 above)
Comment (mrts) [reply src/controller/controller.cpp:325]: In this case use plain `thread->wait()` without `while`:

```diff
-        while (thread->isRunning()) {
-            using namespace std::chrono_literals;
-            thread->wait(100ms);
+            thread->wait();
```

**Comment by martinpaljak** [comment]
I would really much like to test it out for a week or so and have zero crashes before claiming this closed…

**Comment by mrts** [comment]
@martinpaljak sure, feel free to reopen the corresponding issue if you encounter any problems.
